[package]
name = "glowtree"
version = "0.1.0"
authors = ["Edgar <git@edgarluque.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.19.3"
tree-sitter-rust = "0.19.0"
tree-sitter-javascript = "0.19.0"
tree-sitter-python = "0.19.0"
tree-sitter-cpp = "0.19.0"
tree-sitter-java = "0.19.0"
tree-sitter-highlight = "0.19.2"
